export interface KnowledgeEntry {
  id: string;
  name: string;
  category: string;
  aliases: RegExp[];
  refMin?: number;
  refMax?: number;
  unitHint?: RegExp[];
  explanation: string;
  whyItMatters: string;
  highMeaning: string;
  lowMeaning: string;
  associatedHigh: string[];
  associatedLow: string[];
  symptomsHigh: string[];
  symptomsLow: string[];
  preventionHigh: string[];
  preventionLow: string[];
  nutritionHigh: string[];
  nutritionLow: string[];
  lifestyleHigh: string[];
  lifestyleLow: string[];
  followUpHigh: string[];
  followUpLow: string[];
}

const A = (patterns: string[]): RegExp[] => patterns.map((p) => new RegExp(p, 'i'));

export const KNOWLEDGE_BASE: KnowledgeEntry[] = [
  {
    id: 'hemoglobin',
    name: 'Hemoglobin',
    category: 'Complete Blood Count',
    aliases: A([String.raw`\b(?:HGB|Hb|Hemoglobin|Haemoglobin)\b`]),
    refMin: 13,
    refMax: 17,
    unitHint: A([String.raw`g\/?dL`]),
    explanation: 'Hemoglobin is the protein in red blood cells that carries oxygen from your lungs to the rest of your body.',
    whyItMatters: 'It is a core indicator of your blood\'s oxygen-carrying capacity and is used to detect anemia.',
    highMeaning: 'A high hemoglobin level may indicate polycythemia, dehydration, or living at high altitudes.',
    lowMeaning: 'A low hemoglobin level is the classic sign of anemia, which may be caused by iron deficiency, blood loss, or other conditions.',
    associatedHigh: ['Polycythemia vera', 'Dehydration', 'Chronic lung disease', 'Smoking-related high blood oxygen demand'],
    associatedLow: ['Iron deficiency anemia', 'Vitamin B12 or folate deficiency', 'Blood loss', 'Chronic kidney disease'],
    symptomsHigh: ['Headache', 'Dizziness', 'Blurred vision', 'Fatigue', 'Flushed skin'],
    symptomsLow: ['Fatigue and weakness', 'Pale skin', 'Shortness of breath', 'Dizziness', 'Cold hands and feet'],
    preventionHigh: ['Stay well hydrated', 'Avoid smoking', 'Discuss with your doctor if persistent'],
    preventionLow: ['Eat iron-rich foods', 'Get tested for underlying causes', 'Avoid excessive blood loss risk'],
    nutritionHigh: ['Drink plenty of water', 'Limit iron-fortified foods until checked'],
    nutritionLow: ['Leafy greens, beans, and lean red meat', 'Vitamin C with iron-rich meals to improve absorption', 'Fortified cereals'],
    lifestyleHigh: ['Regular aerobic exercise', 'Quit smoking', 'Stay hydrated during exercise'],
    lifestyleLow: ['Balanced meals with iron and B12', 'Gentle exercise to maintain energy'],
    followUpHigh: ['Repeat complete blood count', 'Iron studies', 'Oxygen saturation check'],
    followUpLow: ['Iron studies (ferritin)', 'Vitamin B12 and folate', 'Reticulocyte count'],
  },
  {
    id: 'wbc',
    name: 'White Blood Cells',
    category: 'Complete Blood Count',
    aliases: A([String.raw`\bWBC\b`, String.raw`White Blood Cell`, String.raw`Leukocyte`]),
    refMin: 4,
    refMax: 11,
    unitHint: A([String.raw`\s*10[³3]?\/?[µu]L`, String.raw`\s*×\s*10[³3]`, String.raw`k\/?[µu]L`, String.raw`\/[µu]L`]),
    explanation: 'White blood cells are your immune system\'s defense cells that fight infection and inflammation.',
    whyItMatters: 'Levels change with infections, inflammation, and some immune or bone marrow conditions.',
    highMeaning: 'A high count often indicates an ongoing infection, inflammation, or a reaction to stress or medication.',
    lowMeaning: 'A low count can mean your immune system is weakened, possibly from infections, medications, or bone marrow issues.',
    associatedHigh: ['Bacterial or viral infection', 'Inflammation', 'Stress response', 'Blood disorders (rarely)'],
    associatedLow: ['Viral infections', 'Autoimmune conditions', 'Certain medications', 'Bone marrow disorders'],
    symptomsHigh: ['Fever', 'Tiredness', 'Body aches', 'Signs of infection'],
    symptomsLow: ['Frequent infections', 'Fever', 'Sore throat', 'Feeling run down'],
    preventionHigh: ['Good hygiene to prevent infections', 'Manage stress', 'Stay up to date on vaccines'],
    preventionLow: ['Wash hands often', 'Avoid contact with sick people', 'Get vaccines as recommended'],
    nutritionHigh: ['Fruits and vegetables rich in vitamin C', 'Garlic and ginger', 'Adequate hydration'],
    nutritionLow: ['Protein-rich foods', 'Foods high in zinc and selenium', 'Probiotic foods'],
    lifestyleHigh: ['Adequate sleep', 'Moderate exercise', 'Stress management'],
    lifestyleLow: ['Rest and recovery', 'Gentle activity as tolerated', 'Protective measures against infection'],
    followUpHigh: ['Repeat CBC with differential', 'Blood cultures if fever present', 'ESR / CRP'],
    followUpLow: ['Repeat CBC with differential', 'Viral panels', 'Vitamin B12 levels'],
  },
  {
    id: 'platelets',
    name: 'Platelets',
    category: 'Complete Blood Count',
    aliases: A([String.raw`\bPLT\b`, String.raw`Platelet`, String.raw`Thrombocyte`]),
    refMin: 150,
    refMax: 450,
    unitHint: A([String.raw`(?:10[³3]|k|K)?\s*\/?\s*[µu]L`]),
    explanation: 'Platelets are tiny blood cells that help your blood clot and stop bleeding.',
    whyItMatters: 'Abnormal levels affect your risk of bleeding or clotting.',
    highMeaning: 'A high platelet count may increase clotting risk and can follow inflammation, infection, or iron deficiency.',
    lowMeaning: 'A low count increases bleeding risk and may be linked to immune, medication, or bone marrow causes.',
    associatedHigh: ['Inflammation or infection', 'Iron deficiency', 'Post-surgery state', 'Myeloproliferative disorders'],
    associatedLow: ['Immune thrombocytopenia', 'Medication effects', 'Viral infections', 'Bone marrow suppression'],
    symptomsHigh: ['Usually none', 'Rarely headache or clotting symptoms'],
    symptomsLow: ['Easy bruising', 'Petechiae (tiny red dots)', 'Prolonged bleeding', 'Nosebleeds'],
    preventionHigh: ['Stay hydrated', 'Discuss with doctor if persistently high'],
    preventionLow: ['Avoid aspirin unless prescribed', 'Use a soft toothbrush', 'Be careful with sharp objects'],
    nutritionHigh: ['Antioxidant-rich fruits and vegetables'],
    nutritionLow: ['Foods rich in folate and B12', 'Adequate vitamin K from leafy greens'],
    lifestyleHigh: ['Regular exercise', 'Avoid smoking'],
    lifestyleLow: ['Protect yourself from injury', 'Report unusual bleeding'],
    followUpHigh: ['Repeat CBC', 'Iron studies', 'CRP'],
    followUpLow: ['Repeat CBC', 'Platelet antibody testing', 'Bone marrow evaluation if severe'],
  },
  {
    id: 'glucose',
    name: 'Glucose (Fasting)',
    category: 'Metabolic Panel',
    aliases: A([String.raw`\bFBS\b`, String.raw`Fasting Glucose`, String.raw`Blood Sugar`, String.raw`Glucose\b`]),
    refMin: 70,
    refMax: 100,
    unitHint: A([String.raw`mg\/?dL`, String.raw`mmol\/?L`]),
    explanation: 'Glucose is the sugar in your blood that your body uses for energy.',
    whyItMatters: 'It is the main screening test for diabetes and prediabetes.',
    highMeaning: 'High fasting glucose suggests your body may not be handling sugar well, which can point toward prediabetes or diabetes.',
    lowMeaning: 'Low glucose (hypoglycemia) can cause shakiness and confusion and needs prompt attention.',
    associatedHigh: ['Prediabetes', 'Type 2 diabetes', 'Metabolic syndrome', 'Medication side effects'],
    associatedLow: ['Reactive hypoglycemia', 'Prolonged fasting', 'Certain medications', 'Liver issues'],
    symptomsHigh: ['Increased thirst', 'Frequent urination', 'Blurred vision', 'Fatigue', 'Slow-healing wounds'],
    symptomsLow: ['Shakiness', 'Sweating', 'Irritability', 'Confusion', 'Rapid heartbeat'],
    preventionHigh: ['Limit sugary drinks', 'Maintain a healthy weight', 'Exercise regularly'],
    preventionLow: ['Eat regular meals', 'Avoid long gaps without food'],
    nutritionHigh: ['Whole grains over refined carbs', 'Vegetables and fiber', 'Lean proteins', 'Limit added sugars'],
    nutritionLow: ['Small frequent meals', 'Complex carbohydrates', 'Carry a quick sugar source'],
    lifestyleHigh: ['30 minutes of walking most days', 'Sleep well', 'Manage stress'],
    lifestyleLow: ['Regular meal schedule', 'Carry snacks'],
    followUpHigh: ['Repeat fasting glucose', 'HbA1c', 'Oral glucose tolerance test'],
    followUpLow: ['Repeat glucose measurement', 'Assess diet and medications'],
  },
  {
    id: 'hba1c',
    name: 'HbA1c',
    category: 'Metabolic Panel',
    aliases: A([String.raw`\bHbA1c\b`, String.raw`HbA1C\b`, String.raw`Hemoglobin A1c\b`, String.raw`Glycated Hemoglobin`]),
    refMin: 4,
    refMax: 5.6,
    unitHint: A([String.raw`%`]),
    explanation: 'HbA1c reflects your average blood sugar over the past 2-3 months.',
    whyItMatters: 'It is the best measure of long-term blood sugar control and diabetes risk.',
    highMeaning: 'A high HbA1c indicates consistently elevated blood sugar, suggesting prediabetes or diabetes.',
    lowMeaning: 'A low HbA1c may be seen in anemia or conditions affecting red blood cell lifespan.',
    associatedHigh: ['Prediabetes', 'Type 2 diabetes', 'Insulin resistance'],
    associatedLow: ['Anemia', 'Recent blood loss', 'Hemoglobin disorders'],
    symptomsHigh: ['Increased thirst', 'Frequent urination', 'Fatigue', 'Weight changes'],
    symptomsLow: ['Fatigue', 'Pale skin'],
    preventionHigh: ['Reduce refined carbohydrates', 'Regular exercise', 'Weight management'],
    preventionLow: ['Ensure adequate iron and B12 intake'],
    nutritionHigh: ['High-fiber vegetables', 'Whole grains', 'Lean protein', 'Healthy fats'],
    nutritionLow: ['Iron-rich foods'],
    lifestyleHigh: ['150 minutes of exercise weekly', 'Regular sleep', 'Stress reduction'],
    lifestyleLow: ['Balanced diet with iron-rich foods'],
    followUpHigh: ['Repeat HbA1c', 'Fasting glucose', 'Kidney function'],
    followUpLow: ['Complete blood count', 'Iron studies'],
  },
  {
    id: 'total_cholesterol',
    name: 'Total Cholesterol',
    category: 'Lipid Panel',
    aliases: A([String.raw`Total Cholesterol`, String.raw`Cholesterol, Total`]),
    refMin: 0,
    refMax: 200,
    unitHint: A([String.raw`mg\/?dL`]),
    explanation: 'Total cholesterol measures all the cholesterol in your blood.',
    whyItMatters: 'It is a risk factor screening test for heart and blood vessel disease.',
    highMeaning: 'A high total cholesterol raises long-term risk of cardiovascular disease.',
    lowMeaning: 'Very low cholesterol is less common and is usually not a concern.',
    associatedHigh: ['High-fat diet', 'Genetic lipid disorders', 'Hypothyroidism', 'Metabolic syndrome'],
    associatedLow: ['Malnutrition', 'Hyperthyroidism', 'Chronic liver disease'],
    symptomsHigh: ['Usually none; cholesterol is typically silent'],
    symptomsLow: ['Usually none'],
    preventionHigh: ['Reduce saturated fats', 'Exercise regularly', 'Maintain healthy weight'],
    preventionLow: ['Balanced nutrition'],
    nutritionHigh: ['Oats and barley', 'Nuts and seeds', 'Olive oil', 'Fatty fish'],
    nutritionLow: ['Ensure adequate calories and nutrients'],
    lifestyleHigh: ['Regular aerobic exercise', 'Quit smoking', 'Limit alcohol'],
    lifestyleLow: ['Healthy varied diet'],
    followUpHigh: ['Lipid panel retest', 'Lipoprotein(a) if indicated'],
    followUpLow: ['Lipid panel retest', 'Thyroid function'],
  },
  {
    id: 'ldl',
    name: 'LDL Cholesterol',
    category: 'Lipid Panel',
    aliases: A([String.raw`\bLDL\b`, String.raw`LDL Cholesterol`]),
    refMin: 0,
    refMax: 100,
    unitHint: A([String.raw`mg\/?dL`]),
    explanation: 'LDL is often called "bad" cholesterol because high levels can build up in artery walls.',
    whyItMatters: 'It is a key driver of plaque buildup and cardiovascular risk.',
    highMeaning: 'High LDL increases risk of heart attack and stroke over time.',
    lowMeaning: 'Low LDL is generally favorable.',
    associatedHigh: ['High saturated fat intake', 'Genetic conditions', 'Hypothyroidism', 'Metabolic syndrome'],
    associatedLow: ['No concerning condition typically'],
    symptomsHigh: ['Usually none'],
    symptomsLow: ['Usually none'],
    preventionHigh: ['Limit red and processed meats', 'Increase fiber', 'Exercise'],
    preventionLow: ['Maintain a heart-healthy diet'],
    nutritionHigh: ['Soluble fiber (oats, beans)', 'Nuts and avocado', 'Plant sterols'],
    nutritionLow: ['Continue balanced heart-healthy diet'],
    lifestyleHigh: ['Aerobic exercise most days', 'Weight management', 'Quit smoking'],
    lifestyleLow: ['Keep active lifestyle'],
    followUpHigh: ['Repeat lipid panel', 'Total cardiovascular risk assessment'],
    followUpLow: ['Repeat lipid panel as scheduled'],
  },
  {
    id: 'hdl',
    name: 'HDL Cholesterol',
    category: 'Lipid Panel',
    aliases: A([String.raw`\bHDL\b`, String.raw`HDL Cholesterol`]),
    refMin: 40,
    refMax: 100,
    unitHint: A([String.raw`mg\/?dL`]),
    explanation: 'HDL is often called "good" cholesterol because it helps remove cholesterol from your arteries.',
    whyItMatters: 'Higher HDL is generally protective for heart health.',
    highMeaning: 'High HDL is usually beneficial.',
    lowMeaning: 'Low HDL is associated with higher cardiovascular risk.',
    associatedHigh: ['Regular exercise and healthy diet (beneficial)'],
    associatedLow: ['Sedentary lifestyle', 'Smoking', 'High-carbohydrate diets', 'Insulin resistance'],
    symptomsHigh: ['Usually none'],
    symptomsLow: ['Usually none'],
    preventionHigh: ['Continue healthy habits'],
    preventionLow: ['Exercise regularly', 'Quit smoking', 'Limit refined carbs'],
    nutritionHigh: ['Healthy fats from fish and olive oil'],
    nutritionLow: ['Fatty fish', 'Nuts', 'Avocado', 'Olive oil'],
    lifestyleHigh: ['Continue exercise'],
    lifestyleLow: ['Moderate aerobic exercise most days', 'Avoid smoking'],
    followUpHigh: ['No special follow-up needed'],
    followUpLow: ['Repeat lipid panel', 'Cardiovascular risk assessment'],
  },
  {
    id: 'triglycerides',
    name: 'Triglycerides',
    category: 'Lipid Panel',
    aliases: A([String.raw`\bTG\b`, String.raw`Triglyceride`]),
    refMin: 0,
    refMax: 150,
    unitHint: A([String.raw`mg\/?dL`]),
    explanation: 'Triglycerides are a type of fat in your blood used for energy.',
    whyItMatters: 'High levels are linked to heart disease, stroke, and pancreatitis risk.',
    highMeaning: 'High triglycerides often relate to diet, alcohol, and uncontrolled diabetes.',
    lowMeaning: 'Low triglycerides are generally not a concern.',
    associatedHigh: ['High sugar intake', 'Alcohol', 'Obesity', 'Uncontrolled diabetes'],
    associatedLow: ['Usually no concerning cause'],
    symptomsHigh: ['Usually none', 'Very high levels may cause abdominal pain'],
    symptomsLow: ['Usually none'],
    preventionHigh: ['Limit sugar and alcohol', 'Exercise', 'Weight loss'],
    preventionLow: ['Maintain healthy diet'],
    nutritionHigh: ['Limit refined carbs and sugar', 'Omega-3 rich fish', 'Fiber-rich foods'],
    nutritionLow: ['Balanced meals'],
    lifestyleHigh: ['Aerobic exercise most days', 'Reduce alcohol', 'Manage diabetes if present'],
    lifestyleLow: ['Stay active'],
    followUpHigh: ['Repeat lipid panel', 'Blood sugar and HbA1c', 'Pancreatic enzyme check if very high'],
    followUpLow: ['Repeat lipid panel'],
  },
  {
    id: 'creatinine',
    name: 'Creatinine',
    category: 'Kidney Function',
    aliases: A([String.raw`\bCreatinine\b`]),
    refMin: 0.7,
    refMax: 1.3,
    unitHint: A([String.raw`mg\/?dL`]),
    explanation: 'Creatinine is a waste product your kidneys filter out of the blood.',
    whyItMatters: 'It is the main blood test for kidney function.',
    highMeaning: 'A high creatinine means your kidneys may not be filtering waste as well as they should.',
    lowMeaning: 'Low creatinine is usually not a concern and can relate to low muscle mass.',
    associatedHigh: ['Dehydration', 'Kidney disease', 'Medication effects', 'High-protein states'],
    associatedLow: ['Low muscle mass', 'Pregnancy'],
    symptomsHigh: ['Swelling in feet or ankles', 'Fatigue', 'Reduced urination', 'Shortness of breath'],
    symptomsLow: ['Usually none'],
    preventionHigh: ['Stay well hydrated', 'Control blood pressure', 'Avoid excess NSAIDs'],
    preventionLow: ['Maintain healthy habits'],
    nutritionHigh: ['Adequate water', 'Limit high-sodium foods', 'Discuss protein intake with doctor'],
    nutritionLow: ['Balanced protein intake'],
    lifestyleHigh: ['Regular blood pressure checks', 'Exercise', 'Avoid smoking'],
    lifestyleLow: ['Strength training to maintain muscle'],
    followUpHigh: ['Repeat creatinine', 'eGFR', 'Urine tests', 'Blood pressure monitoring'],
    followUpLow: ['Repeat creatinine if persistent'],
  },
  {
    id: 'alt',
    name: 'ALT',
    category: 'Liver Function',
    aliases: A([String.raw`\bALT\b`, String.raw`Alanine Transaminase`, String.raw`Alanine Aminotransferase`]),
    refMin: 7,
    refMax: 56,
    unitHint: A([String.raw`U\/?L`]),
    explanation: 'ALT is an enzyme mostly found in the liver.',
    whyItMatters: 'Elevated ALT suggests liver cell stress or damage.',
    highMeaning: 'High ALT can indicate fatty liver, medication effects, or viral hepatitis.',
    lowMeaning: 'Low ALT is generally not a concern.',
    associatedHigh: ['Fatty liver disease', 'Viral hepatitis', 'Alcohol-related liver injury', 'Medication effects'],
    associatedLow: ['Usually none'],
    symptomsHigh: ['Fatigue', 'Upper right abdominal discomfort', 'Usually none early on'],
    symptomsLow: ['Usually none'],
    preventionHigh: ['Limit alcohol', 'Healthy weight', 'Vaccination for hepatitis'],
    preventionLow: ['Maintain healthy lifestyle'],
    nutritionHigh: ['Coffee (moderate)', 'Vegetables', 'Limit fried and fatty foods'],
    nutritionLow: ['Balanced diet'],
    lifestyleHigh: ['Reduce alcohol intake', 'Exercise', 'Weight management'],
    lifestyleLow: ['Stay active'],
    followUpHigh: ['Repeat liver panel', 'Hepatitis serology', 'Ultrasound of liver'],
    followUpLow: ['Repeat liver panel if needed'],
  },
  {
    id: 'ast',
    name: 'AST',
    category: 'Liver Function',
    aliases: A([String.raw`\bAST\b`, String.raw`Aspartate Transaminase`, String.raw`Aspartate Aminotransferase`]),
    refMin: 10,
    refMax: 40,
    unitHint: A([String.raw`U\/?L`]),
    explanation: 'AST is an enzyme found in the liver, heart, and muscles.',
    whyItMatters: 'Together with ALT it helps assess liver and muscle health.',
    highMeaning: 'High AST can reflect liver issues or muscle injury.',
    lowMeaning: 'Low AST is generally not a concern.',
    associatedHigh: ['Liver conditions', 'Muscle injury', 'Vigorous exercise', 'Medication effects'],
    associatedLow: ['Usually none'],
    symptomsHigh: ['Fatigue', 'Muscle aches', 'Usually none'],
    symptomsLow: ['Usually none'],
    preventionHigh: ['Limit alcohol', 'Safe exercise habits'],
    preventionLow: ['Maintain healthy lifestyle'],
    nutritionHigh: ['Vegetables and whole grains', 'Limit processed foods'],
    nutritionLow: ['Balanced diet'],
    lifestyleHigh: ['Warm up before exercise', 'Limit alcohol'],
    lifestyleLow: ['Stay active'],
    followUpHigh: ['Repeat liver panel', 'Hepatitis serology'],
    followUpLow: ['Repeat liver panel if needed'],
  },
  {
    id: 'tsh',
    name: 'TSH',
    category: 'Thyroid Function',
    aliases: A([String.raw`\bTSH\b`, String.raw`Thyroid Stimulating Hormone`]),
    refMin: 0.4,
    refMax: 4.0,
    unitHint: A([String.raw`mIU\/?L`, String.raw`uIU\/?mL`]),
    explanation: 'TSH is a hormone that tells your thyroid how active it should be.',
    whyItMatters: 'It is the best screening test for thyroid disorders.',
    highMeaning: 'High TSH usually means an underactive thyroid (hypothyroidism).',
    lowMeaning: 'Low TSH usually suggests an overactive thyroid (hyperthyroidism).',
    associatedHigh: ['Hypothyroidism', 'Hashimoto\'s thyroiditis', 'Recent thyroid medication changes'],
    associatedLow: ['Hyperthyroidism', 'Graves\' disease', 'Excess thyroid medication'],
    symptomsHigh: ['Fatigue', 'Weight gain', 'Cold intolerance', 'Constipation', 'Dry skin'],
    symptomsLow: ['Weight loss', 'Anxiety', 'Heart palpitations', 'Heat intolerance', 'Tremors'],
    preventionHigh: ['Take thyroid medication consistently if prescribed', 'Regular follow-up'],
    preventionLow: ['Regular follow-up with doctor'],
    nutritionHigh: ['Balanced diet with adequate iodine', 'Selenium-rich foods (moderate)'],
    nutritionLow: ['Balanced diet; avoid excess iodine'],
    lifestyleHigh: ['Gentle exercise', 'Stress management'],
    lifestyleLow: ['Limit caffeine', 'Relaxation techniques'],
    followUpHigh: ['Repeat TSH', 'Free T4'],
    followUpLow: ['Repeat TSH', 'Free T4 and Free T3'],
  },
  {
    id: 'vitamin_d',
    name: 'Vitamin D',
    category: 'Vitamins',
    aliases: A([String.raw`Vitamin D\b`, String.raw`25-OH Vitamin D`, String.raw`25 Hydroxyvitamin D`]),
    refMin: 30,
    refMax: 100,
    unitHint: A([String.raw`ng\/?mL`]),
    explanation: 'Vitamin D helps your body absorb calcium and supports bones and immunity.',
    whyItMatters: 'Low vitamin D is very common and affects bone and muscle health.',
    highMeaning: 'High vitamin D can occur with excess supplementation and should be monitored.',
    lowMeaning: 'Low vitamin D weakens bones and can cause fatigue and muscle aches.',
    associatedHigh: ['Excess supplementation', 'High calcium disorders'],
    associatedLow: ['Limited sun exposure', 'Insufficient intake', 'Malabsorption', 'Kidney or liver conditions'],
    symptomsHigh: ['Nausea', 'Weakness', 'Kidney stones (rare)'],
    symptomsLow: ['Fatigue', 'Bone and back pain', 'Muscle weakness', 'Low mood'],
    preventionHigh: ['Review supplement dose with doctor'],
    preventionLow: ['Moderate sun exposure', 'Vitamin D rich foods', 'Supplementation as advised'],
    nutritionHigh: ['Limit additional vitamin D supplements until checked'],
    nutritionLow: ['Fatty fish (salmon, mackerel)', 'Egg yolks', 'Fortified dairy'],
    lifestyleHigh: ['Monitor supplement intake'],
    lifestyleLow: ['Outdoor activity with sun protection', 'Weight-bearing exercise'],
    followUpHigh: ['Repeat vitamin D level', 'Calcium level'],
    followUpLow: ['Repeat vitamin D after supplementation', 'Calcium level'],
  },
  {
    id: 'crp',
    name: 'CRP',
    category: 'Inflammation',
    aliases: A([String.raw`\bCRP\b`, String.raw`C-Reactive Protein`, String.raw`C Reactive Protein`]),
    refMin: 0,
    refMax: 3,
    unitHint: A([String.raw`mg\/?L`]),
    explanation: 'CRP is a protein your liver makes in response to inflammation.',
    whyItMatters: 'It is a general marker of inflammation in the body.',
    highMeaning: 'High CRP signals inflammation from infection, injury, or chronic conditions.',
    lowMeaning: 'Low CRP is normal and desirable.',
    associatedHigh: ['Infections', 'Autoimmune disease', 'Chronic inflammation', 'Recent injury'],
    associatedLow: ['None — low is normal'],
    symptomsHigh: ['Fever', 'Fatigue', 'Pain or swelling', 'Depends on underlying cause'],
    symptomsLow: ['None'],
    preventionHigh: ['Identify and treat underlying cause', 'Healthy lifestyle'],
    preventionLow: ['Continue healthy habits'],
    nutritionHigh: ['Anti-inflammatory foods (berries, leafy greens)', 'Omega-3 fatty acids'],
    nutritionLow: ['Balanced anti-inflammatory diet'],
    lifestyleHigh: ['Manage stress', 'Exercise', 'Sleep well'],
    lifestyleLow: ['Maintain healthy lifestyle'],
    followUpHigh: ['Repeat CRP', 'Investigations based on symptoms'],
    followUpLow: ['No special follow-up'],
  },
  {
    id: 'uric_acid',
    name: 'Uric Acid',
    category: 'Metabolic Panel',
    aliases: A([String.raw`Uric Acid`, String.raw`Urate`]),
    refMin: 3.5,
    refMax: 7.2,
    unitHint: A([String.raw`mg\/?dL`]),
    explanation: 'Uric acid is a waste product from the breakdown of purines in food and cells.',
    whyItMatters: 'High levels can lead to gout and kidney stones.',
    highMeaning: 'High uric acid increases the risk of gout flares and kidney stones.',
    lowMeaning: 'Low uric acid is rarely a concern.',
    associatedHigh: ['Gout', 'Kidney stones', 'High-purine diet', 'Kidney function decline'],
    associatedLow: ['Usually no concerning cause'],
    symptomsHigh: ['Joint pain (often big toe)', 'Swelling and redness of joints', 'Kidney stone pain'],
    symptomsLow: ['Usually none'],
    preventionHigh: ['Limit purine-rich foods', 'Stay hydrated', 'Limit alcohol'],
    preventionLow: ['Maintain healthy habits'],
    nutritionHigh: ['Water', 'Cherries', 'Low-fat dairy', 'Limit organ meats and shellfish'],
    nutritionLow: ['Balanced diet'],
    lifestyleHigh: ['Maintain healthy weight', 'Exercise', 'Limit beer and sugary drinks'],
    lifestyleLow: ['Stay active'],
    followUpHigh: ['Repeat uric acid', 'Kidney function', 'Urine analysis'],
    followUpLow: ['Repeat if needed'],
  },
];
