export const ANALYSIS_SCHEMA = {
  type: 'object',
  properties: {
    overallSummary: { type: 'string' },
    healthScore: { type: 'integer', minimum: 0, maximum: 100 },
    riskLevel: { type: 'string', enum: ['low', 'moderate', 'high'] },
    tests: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: [
          'name',
          'category',
          'value',
          'unit',
          'referenceRange',
          'status',
          'direction',
          'explanation',
          'whyItMatters',
          'highMeaning',
          'lowMeaning',
          'associatedConditions',
          'symptoms',
          'prevention',
          'nutrition',
          'lifestyle',
          'followUpTests',
          'consultAdvice',
        ],
        properties: {
          name: { type: 'string' },
          category: { type: 'string' },
          value: { type: 'string' },
          unit: { type: ['string', 'null'] },
          referenceRange: { type: ['string', 'null'] },
          status: { type: 'string', enum: ['high', 'low', 'normal', 'unknown'] },
          direction: { type: ['string', 'null'], enum: ['high', 'low', null] },
          explanation: { type: 'string' },
          whyItMatters: { type: 'string' },
          highMeaning: { type: ['string', 'null'] },
          lowMeaning: { type: ['string', 'null'] },
          associatedConditions: { type: 'array', items: { type: 'string' } },
          symptoms: { type: 'array', items: { type: 'string' } },
          prevention: { type: 'array', items: { type: 'string' } },
          nutrition: { type: 'array', items: { type: 'string' } },
          lifestyle: { type: 'array', items: { type: 'string' } },
          followUpTests: { type: 'array', items: { type: 'string' } },
          consultAdvice: { type: 'string' },
        },
      },
    },
    insights: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'test', 'insight'],
        properties: {
          id: { type: 'string' },
          test: { type: 'string' },
          insight: { type: 'string' },
        },
      },
    },
    symptoms: { type: 'array', items: { type: 'string' } },
    prevention: { type: 'array', items: { type: 'string' } },
    consult: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['test', 'advice'],
        properties: {
          test: { type: 'string' },
          advice: { type: 'string' },
        },
      },
    },
  },
  additionalProperties: false,
  required: [
    'overallSummary',
    'healthScore',
    'riskLevel',
    'tests',
    'insights',
    'symptoms',
    'prevention',
    'consult',
  ],
} as const;
